<a href="https://colab.research.google.com/github/Nafi14078/Machine_Learning/blob/main/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Machine Learning

# welcome to Numpy


In [71]:
import numpy as np

In [72]:
my_arr=np.array([[1,2,5,7]])

In [73]:
my_arr[0,2]

np.int64(5)

In [74]:
my_arr.shape

(1, 4)

In [75]:
my_arr.dtype

dtype('int64')

In [76]:
my_arr[0,0]=45

In [77]:
my_arr

array([[45,  2,  5,  7]])

In [78]:
listarr=np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8]])

In [79]:
listarr

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [80]:
listarr.dtype

dtype('int64')

In [81]:
listarr.shape

(3, 4)

In [82]:
listarr.size

12

In [83]:
set1=np.array({1,2,2,1,3})

In [84]:
set1

array({1, 2, 3}, dtype=object)

In [85]:
zero1=np.zeros((3,5))

In [86]:
zero1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [87]:
num1=np.arange(2,5)

In [88]:
num1

array([2, 3, 4])

In [89]:
lin1=np.linspace(1,5,4)

In [90]:
lin1

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [91]:
emp=np.empty((2,5))

In [92]:
emp

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [93]:
empl=np.empty_like(lin1)

In [94]:
empl

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [95]:
ide=np.identity(10)

In [96]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [97]:
ide.shape

(10, 10)

In [98]:
ide.size

100

In [99]:
ide.dtype

dtype('float64')

In [100]:
ide.reshape(4,25)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [101]:
ide.ravel()

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [102]:
x=[[1,2,3,4],[3,4,5,6],[5,6,7,8]]

In [103]:
arr=np.array(x)

In [104]:
arr

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [105]:
arr.shape

(3, 4)

In [106]:
arr.size

12

In [107]:
arr.sum(axis=0)

array([ 9, 12, 15, 18])

In [108]:
arr.sum(axis=1)

array([10, 18, 26])

In [109]:
arr.T

array([[1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [110]:
arr.flat

In [111]:
for item in arr.flat:
  print(item)

1
2
3
4
3
4
5
6
5
6
7
8


In [112]:
arr.size

12

In [113]:
arr.ndim

2

In [114]:
arr.nbytes

96

In [115]:
one=np.array([1,2,3,4,5,6,7,8])

In [116]:
one

array([1, 2, 3, 4, 5, 6, 7, 8])

In [117]:
one.argmax()

np.int64(7)

In [118]:
one.argmin()

np.int64(0)

In [119]:
one.argsort()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [120]:
arr

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [121]:
arr.argmax()

np.int64(11)

In [122]:
arr.argmin()

np.int64(0)

In [123]:
arr.argsort()

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [124]:
arr.argmax(axis=0)

array([2, 2, 2, 2])

In [125]:
arr.argmax(axis=1)

array([3, 3, 3])

In [126]:
arr.argmin(axis=0)

array([0, 0, 0, 0])

In [127]:
arr.argmin(axis=1)

array([0, 0, 0])

In [128]:
arr.ravel()

array([1, 2, 3, 4, 3, 4, 5, 6, 5, 6, 7, 8])

In [129]:
arr.reshape((4,3))

array([[1, 2, 3],
       [4, 3, 4],
       [5, 6, 5],
       [6, 7, 8]])

In [130]:
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [131]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [132]:
arr1.size

12

In [133]:
arr.shape

(3, 4)

In [134]:
arr1.shape

(3, 4)

In [135]:
arr+arr1

array([[ 2,  4,  6,  8],
       [ 8, 10, 12, 14],
       [14, 16, 18, 20]])

In [136]:
arr-arr1

array([[ 0,  0,  0,  0],
       [-2, -2, -2, -2],
       [-4, -4, -4, -4]])

In [137]:
arr*arr1

array([[ 1,  4,  9, 16],
       [15, 24, 35, 48],
       [45, 60, 77, 96]])

In [138]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [139]:
arr1.sum()

np.int64(78)

In [140]:
arr1.max()

np.int64(12)

In [141]:
arr1.min()

np.int64(1)

In [142]:
arr1.sum(axis=0)

array([15, 18, 21, 24])

In [143]:
l1=[1,2,3,4]

In [144]:
l2=[3,4,5,6]

In [145]:
l3=l1+l2

In [146]:
l3

[1, 2, 3, 4, 3, 4, 5, 6]

In [148]:
[67,7,6]+[2,3,4]

[67, 7, 6, 2, 3, 4]

In [150]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [151]:
np.where(arr1>5)

(array([1, 1, 1, 2, 2, 2, 2]), array([1, 2, 3, 0, 1, 2, 3]))

In [152]:
np.count_nonzero(arr1)

12

In [153]:
np.nonzero(arr1)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))

In [154]:
import sys

In [155]:
py_ar=[1,2,3,4]

In [156]:
num_ar=np.array(py_ar)

In [158]:
sys.getsizeof(1)*len(py_ar)

112

In [160]:
num_ar.itemsize*num_ar.size

32

In [161]:
arr1.tolist()

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [162]:
arr1.ndim

2

In [163]:
arr1.sort()

In [164]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [165]:
arr1[2,1]=1

In [166]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  1, 11, 12]])

In [167]:
arr1.sort()

In [168]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 1,  9, 11, 12]])